version: '3'
services:
  data_collecter:
    build: ./data_collecter
    image: yujik/cryptowatch-datastore-data-collecter:3.0
    platform: linux/amd64
    volumes:
      - type: bind
        source: "./data"
        target: "/data"
      - type: bind
        source: "./.env"
        target: "/.env"
  api_server:
    build: ./api_server
    image: yujik/cryptowatch-datastore-api_server:3.0
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: "./data"
        target: "/data"
      - type: bind
        source: "./.env"
        target: "/.env"